import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styled from 'styled-components'
const Home: NextPage = () => {
  const [msgError, setMsgError] = useState('')
  const [valorInput, setValorInput] = useState()
  // guarda o valor digitado
  const [dadosAPI, setDadosAPI] = useState({
    uf: '',
    city: '',
    street: ''
  })
  // dados que vem da API e é armazenado

  const handleButton = () => {
    axios
      .get('https://cep.awesomeapi.com.br/json/' + valorInput)
      .then(response => {
        const { data } = response
        setDadosAPI({
          uf: data.state,
          city: data.city,
          street: data.address
        })
      })
      .catch(({ response }) => {
        const { data } = response
        setMsgError(data.message)
      })
  }
  const handleInput = value => {
    if (value.length < 10) {
      setValorInput(value.replace(/\D/g, '').replace(/(\d{5})(\d{1})/, '$1-$2'))

      // colocar traço e limitar somente a numeros
    }
  }

  useEffect(() => {
    setMsgError('')
    setDadosAPI({
      uf: '',
      city: '',
      street: ''
    })
  }, [valorInput])

  // função de buscar na API
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContainerCep onSubmit={e => e.preventDefault()}>
        <div>
          <p>CEP</p>
          <input
            value={valorInput}
            onChange={(event: any) => handleInput(event.target.value)}
          />
        </div>
        <button type="submit" onClick={() => handleButton()}>
          BUSCAR
        </button>
        {!!msgError && <p>{msgError}</p>}
        {/* função do botão */}
      </ContainerCep>
      <ContainerResults>
        {' '}
        <div>
          <p>UF</p>
          <span>{dadosAPI.uf}</span>
        </div>{' '}
        <div>
          <p>Cidade</p>
          <span>{dadosAPI.city}</span>
        </div>{' '}
        <div>
          <p>Rua</p>
          <span>{dadosAPI.street}</span>
        </div>
      </ContainerResults>
    </Container>
  )
}
const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  height: 100vh;
  justify-content: center;
  background-color: #fafafa;
  gap: 32px;
  background-image: url(https://images4.alphacoders.com/936/936378.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  padding: 16px;
`
const ContainerCep = styled.form`
  display: flex;
  box-shadow: 0px 1px 3px #c9c9c9;
  background-color: white;
  padding: 24px;
  gap: 16px;
  border-radius: 24px;
  width: 100%;
  max-width: 500px;
  flex-direction: column;
  gap: 32px;

  > div {
    display: flex;
    flex-direction: column;
    width: 100%;
    > p {
      font-size: 20px;
      font-weight: 500;
      color: #707070;
      margin-bottom: 6px;
    }
    > input {
      width: 100%;
      height: 48px;
      border-radius: 6px;
      border: 1px solid #929292;
      font-size: 18px;
    }
  }

  > button {
    display: flex;
    border: none;
    align-items: center;
    justify-content: center;
    width: 50%;
    height: 40px;
    background-color: #007fff;
    border-radius: 6px;
    align-self: flex-end;
    font-size: 20px;
    color: white;
    box-shadow: 0px 1px 3px #c9c9c9;
    font-size: 18px;
    font-weight: 600;
    @media (max-width: 532px) {
      width: 100%;
    }
    cursor: pointer;
  }
`
const ContainerResults = styled.div`
  display: flex;
  box-shadow: 0px 1px 3px #c9c9c9;
  background-color: white;
  padding: 24px;
  gap: 16px;
  border-radius: 24px;
  width: 500px;
  flex-direction: column;
  gap: 32px;

  > div {
    display: flex;
    flex-direction: column;
    width: 100%;
    > p {
      font-size: 20px;
      font-weight: 500;
      color: #707070;
      margin-bottom: 6px;
    }
    > span {
      display: flex;
      align-items: center;
      width: 100%;
      height: 48px;
      border-radius: 6px;
      border: 1px solid #929292;
      font-size: 18px;
    }
  }
`
export default Home
